### ISSUE TITLE
나중에 백 들어오면 해야할것

### ISSUE THREAD

**Issue by SEOKKAMONI** [Bamdoliro/Stupetition-client-V1#19]
### ✨ Describe

.

### ✅ Tasks

- [x] 동의하기를 구현했지만 cors 고쳐지면 한번더 확인
- [x] 삭제기능은 구현했지만 자기것만 삭제할수있게
- [x] 디자인 되면 어드민 댓글 구현
- [x] comment 어드민 학생 구분해서 체크 표시
- [x] answer api 통신 한번더 확인하기
