### ISSUE TITLE
네이밍 정리랑 value 좀 줍시다

### ISSUE THREAD

**Issue by SEOKKAMONI** [Bamdoliro/Stupetition-client-V1#43]
### ✨ Describe

- Input에 value 안준게 꽤 있습니다
- 네이밍 정리도 필요해보입니다
- commit 내역에 보면 리뷰 있습니다 리뷰 반영을 해야합니다

### ✅ Tasks

- [x] Input에 value 안준게 꽤 있습니다
- [ ] 네이밍 정리도 필요해보입니다
- [x] commit 내역에 보면 리뷰 있습니다 리뷰 반영을 해야합니다

### 🙋🏻 More

.

**Comment by SEOKKAMONI** [comment]
네이밍 깔끔한ㄷ?
